### ISSUE TITLE
Trouble with rake db:bootstrap

### ISSUE THREAD

**Issue by nhunzaker** [jsqu99/spree_flexi_variants#23]
I'm on Spree 0.70.x, and I've configured my gemfile like so:

``` ruby
git "https://github.com/jsqu99/spree_flexi_variants.git", :branch => "spree-0-70-stable" do
  gem 'spree_flexi_variants'
end
```

However when I rake db:boostrap here's what I get:

```
/path/to/active_support/whiny_nil.rb:48:in `method_missing': undefined method `set_preference' for nil:NilClass (NoMethodError)
```

Any thoughts?

**Comment by jsqu99** [comment]
yuk.  pre spree-1.0 prefs always caused me tons of troubles.  full stack trace please?  i remember having to guard against setting preferences during rake execution.  you might want to comment out the prefs setting code during rake, then uncomment.  Just do a bundle show spree_flexi_variants , go into the code & comment out, rerun, then uncomment.  hopefully that will work for you.

**Comment by nhunzaker** [comment]
Okay, I'll give it a go. In the meantime, here's the trace.

```
/Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.1.3/lib/active_support/whiny_nil.rb:48:in `method_missing': undefined method `set_preference' for nil:NilClass (NoMethodError)
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/spree_core-0.70.3/lib/spree/preference_access.rb:18:in `block in set'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/spree_core-0.70.3/lib/spree/preference_access.rb:17:in `each'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/spree_core-0.70.3/lib/spree/preference_access.rb:17:in `set'
    from /Users/nate/Sites/kkane/config/initializers/spree_config.rb:1:in `<top (required)>'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:234:in `load'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:234:in `block in load'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:234:in `load'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.1.3/lib/rails/engine.rb:556:in `block (2 levels) in <class:Engine>'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.1.3/lib/rails/engine.rb:555:in `each'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.1.3/lib/rails/engine.rb:555:in `block in <class:Engine>'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.1.3/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.1.3/lib/rails/initializable.rb:30:in `run'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.1.3/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.1.3/lib/rails/initializable.rb:54:in `each'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.1.3/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.1.3/lib/rails/application.rb:96:in `initialize!'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.1.3/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/nate/Sites/kkane/config/environment.rb:5:in `<top (required)>'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in `require'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in `block in require'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in `require'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.1.3/lib/rails/application.rb:83:in `require_environment!'
    from /Users/nate/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.1.3/lib/rails/commands.rb:22:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by jsqu99** [comment]
what do you have in:  /Users/nate/Sites/kkane/config/initializers/spree_config.rb

I'd comment out everything during the rake task

**Comment by nhunzaker** [comment]
```
# Load the rails application
require File.expand_path('../application', __FILE__)

# Initialize the rails application
Kkane::Application.initialize!

ActiveRecord::Base.include_root_in_json = true
```

Nothing fancy, just initializing the application, I'll give it a try. EDIT: Of course that won't work, ActiveRecord won't establish a connection.

**Comment by nhunzaker** [comment]
Commenting out `lines 18 and 20 of /spree/preferences_access.rb` worked like magic, thanks!

**Comment by nhunzaker** [comment]
Just a heads up for future developers, another one of our developers was also able to run the migrations by commenting out the following in `[app_directory]/config/initializers/spree_config.rb`.

``` ruby

#Spree::Config.set(logo: "store/logo.png")

```

**Comment by jsqu99** [comment]
glad to get you on track!
