### ISSUE TITLE
production unicorn issue with mount_uploader.

### ISSUE THREAD

**Issue by peterberkenbosch** [jsqu99/spree_flexi_variants#51]
Running this on a box that used the Spree Deployments Services.. running it local in development mode with webrick I have no issues.. running it on the unicorn box keeps rendering this issue..

```
/data/spree/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/dynamic_matchers.rb:50:in `method_missing': undefined method `mount_uploader' for #<Class:0x000000058fe648> (NoMethodError)
    from /data/spree/shared/bundle/ruby/1.9.1/bundler/gems/spree_flexi_variants-7c24a3a6b32d/app/models/spree/customized_product_option.rb:8:in `<class:CustomizedProductOption>'
    from /data/spree/shared/bundle/ruby/1.9.1/bundler/gems/spree_flexi_variants-7c24a3a6b32d/app/models/spree/customized_product_option.rb:4:in `<module:Spree>'
    from /data/spree/shared/bundle/ruby/1.9.1/bundler/gems/spree_flexi_variants-7c24a3a6b32d/app/models/spree/customized_product_option.rb:1:in `<top (required)>'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `block in require'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `require'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:359:in `require_or_load'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:313:in `depend_on'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:225:in `require_dependency'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/engine.rb:439:in `block (2 levels) in eager_load!'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/engine.rb:438:in `each'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/engine.rb:438:in `block in eager_load!'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/engine.rb:436:in `each'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/engine.rb:436:in `eager_load!'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/application/railties.rb:8:in `each'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/application/railties.rb:8:in `all'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/engine.rb:434:in `eager_load!'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/application/finisher.rb:53:in `block in <module:Finisher>'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/initializable.rb:30:in `instance_exec'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/initializable.rb:30:in `run'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/initializable.rb:54:in `each'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/initializable.rb:54:in `run_initializers'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/application.rb:136:in `initialize!'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /data/spree/releases/20120627165425/config/environment.rb:5:in `<top (required)>'
    from config.ru:4:in `require'
    from config.ru:4:in `block in <main>'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:51:in `instance_eval'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:51:in `initialize'
    from config.ru:1:in `new'
    from config.ru:1:in `<main>'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/unicorn-4.2.1/lib/unicorn.rb:44:in `eval'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/unicorn-4.2.1/lib/unicorn.rb:44:in `block in builder'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/unicorn-4.2.1/bin/unicorn_rails:139:in `call'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/unicorn-4.2.1/bin/unicorn_rails:139:in `block in rails_builder'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/unicorn-4.2.1/lib/unicorn/http_server.rb:694:in `call'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/unicorn-4.2.1/lib/unicorn/http_server.rb:694:in `build_app!'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/unicorn-4.2.1/lib/unicorn/http_server.rb:136:in `start'
    from /data/spree/shared/bundle/ruby/1.9.1/gems/unicorn-4.2.1/bin/unicorn_rails:209:in `<top (required)>'
    from /data/spree/shared/bundle/ruby/1.9.1/bin/unicorn_rails:23:in `load'
    from /data/spree/shared/bundle/ruby/1.9.1/bin/unicorn_rails:23:in `<main>'
```

**Comment by peterberkenbosch** [comment]
Looks like a gem loading issue.. "solved" it by adding carrierwave to the host-app Gemfile.
